[build]
target = "xtensa-esp32s3-espidf"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "cargo espflash flash --elf"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"

# 避免 Windows 路径过长错误
CARGO_TARGET_DIR = { value = "G:/esp-build", relative = false }
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
monitor = "cargo espflash flash --monitor"
